### ISSUE TITLE
Error: Unknown tag 'jekyllgram' in /_layouts/music.html

### ISSUE THREAD

**Issue by aidenva** [benbarber/jekyll-instagram#8]
Hi, first of all thank you so much for this plugin.

I have been trying to follow the guidelines & my intuition to get this to work, but I keep running into this error. I have the API as the environmental variable, copied the jekyllgram.rb plugin into the _plugin folder at root, and added the display snippet in the .html layout that I needed, but it kept saying that the tag cannot be found. Was I supposed to add something else to the layout?

**Comment by benbarber** [comment]
Hi, the directory you places it under should be `_plugins` rather than just `_plugin` like you mentioned. Maybe thats the issue for you?

If not do you have a repo with the issue that I can take a look at?

**Comment by benbarber** [comment]
Hi, the error you are getting will be due to the plugin not getting loaded. This can happen when deploying to GitHub pages as by default they only allow some whitelisted plugins.

I have added a section to the [readme](https://github.com/benbarber/jekyll-instagram#notes) with more information on this, along with a working example.
